### ISSUE TITLE
Dependencies need updating

### ISSUE THREAD

**Issue by dlong500** [pofider/node-wkhtmltopdf-installer#2]
All of the dependencies have updated versions.  Can these get updated?  Particularly the `bin-wrapper` module has had many updates and no longer depends on the deprecated `find-file` module (which gives a warning every time `npm install` gets run.

**Comment by pofider** [comment]
Hi, yes I can do it, but don't you want to test it with latest versions and make the pull request?

**Comment by dlong500** [comment]
I just thought I'd open an issue first because I'm not clear on how hard it might be.  I figured there was at least a chance it would simply be an issue of changing the package.json dependency versions with no other updates required.  If it goes beyond that I can do some testing hopefully soon, but not immediately.  Thanks for the response.

**Comment by pofider** [comment]
Yes it should be just about updating package.json if we are lucky. 

I will keep this for you. Thank you for your time.

**Comment by pofider** [comment]
Updated in 0.2.0
