### ISSUE TITLE
Gem is broken now that gna.org has shut down

### ISSUE THREAD

**Issue by CyberFerret** [pofider/node-wkhtmltopdf-installer#7]
I went to deploy my Ruby/Sinatra project using this gem to a new live server this morning, but noted that the `bundle install` command on the server fails with a timeout waiting for `downloads.gna.org`.

I believe that service has shut down now, and that the *wkhtmltopdf* project is now hosted on Github solely.

Will this project be updated to pull the latest `wkhtmltopdf` source files from Github rather than gna.org?

**Comment by pofider** [comment]
we don't download the binary from the url you are pointing to.
This is npm package, not a ruby one. I believe you are at the wrong place.
